#include <cstring>
#include <cstdlib>
#include <vector>
#include <string>
#include <iostream>
#include <stdio.h>
#include <assert.h>
#include "caffe/caffe.hpp"
#include "caffe/util/io.hpp"
#include "caffe/blob.hpp"
#include "opencv2/opencv.hpp"
#include "time.h"
#include "CAFFE_classifier.h"
#include "fstream"
#include <numeric>
#include <stdlib.h>
#include <string>
#include <iostream>
#include "BlackBox.h"
